### ISSUE TITLE
Plugin Manager Broken

### ISSUE THREAD

**Issue by ethanpil** [StanDog/npp-phpautocompletion#2]
Tried to install via NPP plugin manager, but installation failed. Is this related to move from SF to GitHub?

**Comment by StanDog** [comment]
Yes, this plugin has moved recently from SourceForge to GitHub. The NPP Plugin Manager was not updated until now (afaik) and still tries to download the files from SF and fails because I removed all files from there. There is a plugin repository from where the NPP Plugin Manager takes the download URLs. I updated the URL for my plugins but it takes some weeks until the NPP Plugin Manager will use them too (I can' change this, sorry). You have to wait until Dave Brotherstone updates the Plugin Manager or you can download this plugin from here: https://github.com/StanDog/npp-phpautocompletion/raw/master/RELEASES/ccc_1.4.1.zip

You'll always find the newest download link here: https://github.com/StanDog/npp-phpautocompletion/blob/master/README.md
