### ISSUE TITLE
class inspector and autocomplete improvement

### ISSUE THREAD

**Issue by the-liquid-metal** [StanDog/npp-phpautocompletion#3]
Hello.
Thanks for this precious plugin.
- It seems that attributes and methods shown in the class inspector are belongs to the last file in the file list, if the inspector finds more than 1 file which has same name. Can you fix/modify this to become each file has it own attribute & property?
- can it has multiple root directories?
- is namespace in the referred source code is recognized? if yes, it would be better if the file name in the class inspector is replaced with namespace
- is namespace in the refering source code is recognized? if no, could it be, and display the autocomplete list based on the class with proper namespace?

**Comment by StanDog** [comment]
Thank you for your suggestions!

* Well, this is a little bit tricky. The plugin automatically performs class inheritance based on all the files it parses under the root directory. Also, the inheritance works by class name, not by file. A file based autocompletion is somewhat difficult from the logical point of view - how would the autocompletion popup know which of the identical classes' properties it should show? Afaik even in PHP it is not possible to create two classes with identical names without getting a parser error.
* Multiple root directories are planned for one of the next upcoming releases.
* Namespaces are currently not supported but they are planned for one of the future versions. Using the namespaces instead of file names is a good idea.
